# SPDX-License-Identifier: GPL-2.0-only

load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")

# Only select targets declared by each platform/variant in the modules repository.
# Module groups include their constituent drivers once.
_TECHPACK_MODULES = {
    "//vendor/qcom/sm8850-modules/nxp/opensource/driver:{}_nxp-nci": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/audio-kernel:{}_modules": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/bt-kernel:{}_bt_fm_swr": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/bt-kernel:{}_btfm_slim_codec": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/bt-kernel:{}_btfmcodec": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/bt-kernel:{}_btpower": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/bt-kernel:{}_radio-i2c-rtc6226-qca": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/bt-kernel:{}_spi_cnss_proto": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/bt-kernel:{}_thqspi_proto": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/camera-kernel:{}_camera": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/data-kernel/drivers/smem-mailbox:{}_smem_mailbox": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/dataipa:{}_gsim": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/dataipa:{}_ipam": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/dataipa:{}_ipanetm": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/dataipa:{}_ipatestm": [
        "canoe_consolidate",
        "lahaina_consolidate",
        "sun_consolidate",
        "vienna_consolidate",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet-ext/aps:{}_aps": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet-ext/mem:{}_rmnet_mem": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet-ext/offload:{}_offload": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet-ext/perf:{}_perf": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet-ext/perf_tether:{}_perf_tether": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet-ext/sch:{}_sch": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet-ext/shs:{}_shs": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet-ext/wlan:{}_wlan": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet:{}_rmnet_core": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/datarmnet:{}_rmnet_ctl": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/display-drivers:{}_msm_drm": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/dsp-kernel:{}_frpc-adsprpc": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "x1p42100_consolidate",
        "x1p42100_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/dsp-kernel:{}_frpc-trusted-adsprpc": [
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/eva-kernel:{}_eva_modules": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/graphics-kernel:{}_msm_kgsl": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/mm-drivers/hfi_core:{}_msm_hfi_core": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/mm-drivers/hw_fence:{}_msm_hw_fence": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/mm-drivers/msm_ext_display:{}_msm_ext_display": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/mm-drivers/sync_fence:{}_sync_fence": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/mmrm-driver:{}_mmrm_driver": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_hdcp2p2_test": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_hdcp_qseecom_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_qce50_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_qcedev-mod_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_qcedev_fe_dlkm": [
        "autogvm_consolidate",
        "autogvm_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_qcrypto-msm_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_qrng_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_qseecom_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_seccam_test_driver": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_si_core_test": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_smcinvoke_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_smmu_proxy_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_tmecom-intf_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_tornado_mod": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/securemsm-kernel:{}_tz_log_dlkm": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/spu-kernel:{}_spcom": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/spu-kernel:{}_spss_utils": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/synx-kernel:{}_modules": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/video-driver:{}_video_modules": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
        "sun-tuivm_debug-defconfig",
        "sun-tuivm_defconfig",
        "sun-oemvm_debug-defconfig",
        "sun-oemvm_defconfig",
        "canoe-tuivm_debug-defconfig",
        "canoe-tuivm_defconfig",
        "canoe-oemvm_debug-defconfig",
        "canoe-oemvm_defconfig",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/platform:{}_cnss2": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/platform:{}_cnss_nl": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/platform:{}_cnss_plat_ipc_qmi_svc": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/platform:{}_cnss_prealloc": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/platform:{}_cnss_utils": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/platform:{}_icnss2": [
        "canoe_consolidate",
        "canoe_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/platform:{}_wlan_firmware_service": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "lahaina_consolidate",
        "lahaina_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_kiwi-v2": [
        "canoe_consolidate",
        "canoe_perf",
        "autogvm_consolidate",
        "autogvm_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_peach": [
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_peach-v2": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_qca6390": [
        "autogvm_consolidate",
        "autogvm_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_qca6490": [
        "autogvm_consolidate",
        "autogvm_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_qca6490_cnss2": [
        "autogvm_consolidate",
        "autogvm_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_qca6750": [
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_qcn7605": [
        "autogvm_consolidate",
        "autogvm_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_wcn7750": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/qcom/opensource/wlan/qcacld-3.0:{}_qca_cld_wcn7760": [
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/st/opensource/driver:{}_stm_nfc_i2c": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
    ],
    "//vendor/qcom/sm8850-modules/st/opensource/eSE-driver:{}_stm_st54se_gpio": [
        "canoe_consolidate",
        "canoe_perf",
        "sun_consolidate",
        "sun_perf",
        "vienna_consolidate",
        "vienna_perf",
    ],
}

def get_techpack_modules(target, msm_target, variant):
    build_variant = "{}_{}".format(msm_target, variant)
    return [
        label.format(target)
        for label, variants in _TECHPACK_MODULES.items()
        if build_variant in variants
    ]

def define_techpack_modules(target, msm_target, variant):
    techpack_targets = get_techpack_modules(target, msm_target, variant)
    if not techpack_targets:
        return []

    pkg_files(
        name = "{}_all_vendor_module_dist_files".format(target),
        srcs = techpack_targets,
        strip_prefix = strip_prefix.files_only(),
        visibility = ["//visibility:private"],
    )
    pkg_install(
        name = "{}_all_vendor_module_dist".format(target),
        srcs = [":{}_all_vendor_module_dist_files".format(target)],
        destdir = "out/msm-kernel-{}/techpack".format(target),
    )
    return techpack_targets
